# frozen_string_literal: true

source 'https://rubygems.org'

gem 'ruby-lsp'
gem 'ruby-lsp-rails'

gem 'rails', '7.2.2.1'
gem 'bootsnap', '1.18.6'
gem 'railties', '7.2.2.1'

gem 'erb_lint', '0.9.0'
gem 'rubocop', '1.80.0'
gem 'rubocop-rails', '2.33.3'
